ALTER TABLE EX1_023047.CITY
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.CITY CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.CITY
(
  CITY_ID                   NUMBER,
  CITY                      NVARCHAR2(100),
  STATE_PROVINCE            NVARCHAR2(100),
  BILLING_CITY              NVARCHAR2(100),
  BILLING_STATE_PROVINENCE  NVARCHAR2(100),
  BILLING_COUNTRY           NVARCHAR2(100),
  BILLING_POSTAL_COUNTRY    NVARCHAR2(100)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023047.CULTURE
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.CULTURE CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.CULTURE
(
  CULTURE_ID   NUMBER,
  NOMBRE       NVARCHAR2(200),
  DESCRIPCION  NVARCHAR2(200)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023047.CUSTOMER
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.CUSTOMER
(
  CUSTOMER_ID  NUMBER,
  ADDRESS_ID   NUMBER,
  EMAIL        NVARCHAR2(100),
  COMPANY      NVARCHAR2(100),
  L_NAME       NVARCHAR2(100),
  F_NAME       NVARCHAR2(100)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023047.DIRECCION
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.DIRECCION CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.DIRECCION
(
  ADDRESS_ID       NUMBER,
  BILLING_ADDRESS  NVARCHAR2(250),
  ADDRESS          NVARCHAR2(250),
  POSTAL_CODE      NUMBER,
  CITY_ID          NUMBER,
  CUSTOMER_ID      NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023047.ORDERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.ORDERS CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.ORDERS
(
  ORDER_ID     NUMBER,
  ORDER_DATE   DATE,
  SUBTOTAL     NUMBER,
  TAX_AMOUNT   NUMBER,
  CUSTOMER_ID  NUMBER,
  ADDRESS_ID   NUMBER,
  UNIT_PRICE   NUMBER,
  SHIPPING     NUMBER,
  SHIP_METHOD  NVARCHAR2(200)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023047.PRODUCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.PRODUCT
(
  PRODUCT_ID           NUMBER,
  PESO                 NUMBER,
  COLOR                NVARCHAR2(50),
  CATEGORIA_SERVICIO   NVARCHAR2(250),
  LIST_PRICE           NUMBER,
  TAMANO               NVARCHAR2(10),
  UNIT_PRICE_DISCOUNT  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE EX1_023047.PRODUCT_CULTURE CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.PRODUCT_CULTURE
(
  CULTURE_ID  NUMBER,
  PRODUCT_ID  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX EX1_023047.CITY_PK ON EX1_023047.CITY
(CITY_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023047.CULTURE_PK ON EX1_023047.CULTURE
(CULTURE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023047.CUSTOMER_PK ON EX1_023047.CUSTOMER
(CUSTOMER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023047.DIRECCION_PK ON EX1_023047.DIRECCION
(ADDRESS_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023047.ORDERS_PK ON EX1_023047.ORDERS
(ORDER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023047.PRODUCT_PK ON EX1_023047.PRODUCT
(PRODUCT_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE EX1_023047.ORDER_PRODUCT
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023047.ORDER_PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE EX1_023047.ORDER_PRODUCT
(
  ORDER_ID    NUMBER,
  PRODUCT_ID  NUMBER,
  QUANTITY    NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX EX1_023047.ORDER_PRODUCT_PK ON EX1_023047.ORDER_PRODUCT
(ORDER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );




--Constraints
--ciudad-direccion
ALTER TABLE EX1_023047.DIRECCION
 ADD CONSTRAINT DIRECCION_R01 
  FOREIGN KEY (CITY_ID) 
  REFERENCES EX1_023047.CITY (CITY_ID)
  ENABLE VALIDATE;

--orden-customer
ALTER TABLE EX1_023047.ORDERS
 ADD CONSTRAINT ORDERS_R01 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES EX1_023047.CUSTOMER (CUSTOMER_ID)
  ENABLE VALIDATE;

--orden_op
ALTER TABLE EX1_023047.ORDER_PRODUCT
 ADD CONSTRAINT ORDER_PRODUCT_R01 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES EX1_023047.ORDERS (ORDER_ID)


--product to op
ALTER TABLE EX1_023047.PRODUCT
 ADD CONSTRAINT PRODUCT_R01 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES EX1_023047.ORDER_PRODUCT (PRODUCT_ID)
  ENABLE VALIDATE;



alter table EX1_023047.DIRECCION
add constraint fk_customer
foreign key (CUSTOMER_ID)
references EX1_023047.CUSTOMER(CUSTOMER_ID);

--Constraints
alter table EX1_023047.order_product
add constraint fk_order_product
foreign key (product_id)
references EX1_023047.product(product_id);


ALTER TABLE EX1_023047.product_culture
    ADD CONSTRAINT fk_product_1 FOREIGN KEY (product_id)
        REFERENCES EX1_023047.product (product_id);

ALTER TABLE EX1_023047.product_culture
    ADD CONSTRAINT fk_product_2 FOREIGN KEY (culture_id)
        REFERENCES EX1_023047.culture (culture_id);

